# Generated by Django 2.0.2 on 2019-05-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190509_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='exp_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
