# Generated by Django 2.0.2 on 2019-05-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.Location'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='skill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.Skill'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
