# Generated by Django 2.2.1 on 2019-06-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20190629_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.Location'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='skill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.Skill'),
        ),
        migrations.AlterField(
            model_name='blogprofile',
            name='source',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalartistprofile',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='booking.Location'),
        ),
        migrations.AlterField(
            model_name='historicalartistprofile',
            name='skill',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='booking.Skill'),
        ),
        migrations.AlterField(
            model_name='historicalblogprofile',
            name='source',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
