# Generated by Django 2.2.1 on 2019-07-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_auto_20190630_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogprofile',
            name='keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blogprofile',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalblogprofile',
            name='keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='historicalblogprofile',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.Location'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='skill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.Skill'),
        ),
        migrations.AlterField(
            model_name='historicalartistprofile',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='booking.Location'),
        ),
        migrations.AlterField(
            model_name='historicalartistprofile',
            name='skill',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='booking.Skill'),
        ),
    ]
